name: Simple If Demo
# change
on:
  push:
  
jobs:
  imran-rulez:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    
      - name: Echo 1
        run: echo "1"
        if: github.actor == 'csfeeser'
        # ^ this step only runs if the repo owner is Chad Feeser
        
      - name: Echo 2
        run: echo "2"
        if: github.ref == 'refs/heads/main'
        # ^ this step only runs if the commit is being made to the main branch
        
      - name: Echo 3
        run: echo "3"
        if: contains(github.event.head_commit.message, 'jabberwocky')
        # ^ check if the commit message contains a certain string
