name: Simple If Demo

on:
  push:
  
jobs:
  test-if:
    runs-on: ubuntu-latest
    steps:
    
      - name: Echo 1
        run: echo "1"
        if: 2 == 3
        # ^ condition that must equate to TRUE in order the step to run
        
      - name: Echo 2
        run: echo "2"
        if: 2 != 3
        
      - name: Echo 3
        run: echo "3"
        if: 5 > 10
