name: Simple If Demo

on:
  push:
  
jobs:
  test-if:
    runs-on: ubuntu-latest
    steps:
    
      - name: Echo 1
        run: echo "1"
        if: github.actor == 'csfeeser'
        # ^ this step only runs if the repo owner is Chad Feeser
        
      - name: Echo 2
        run: echo "2"
        if: github.ref == 'refs/heads/main'
        # ^ this step only runs if the commit is being made to the main branch
        
