name: jorb two

on:
  issues:
    types:
      - opened

jobs:
  job-two:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Barf checks in
        run: |
          echo "'I'm a mog! Half man, half dog! I'm my own best friend.'"
          echo "Issue number: #${{ github.event.issue.number }}"
          echo "Issue title:  ${{ github.event.issue.title }}"
